owner: GeiserX
git-repo-url: https://github.com/GeiserX/duplicacy-container
charts-repo-url: https://geiserx.github.io/duplicacy-container
packages-with-index: false
index-path: index.yaml
release-name-template: "{{ .Name }}-{{ .Version }}"
