{{- if .Values.cron.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "duplicacy.fullname" . }}-config
  labels:
    {{- include "duplicacy.labels" . | nindent 4 }}
data:
  DUPLICACY_THREADS: {{ .Values.cron.env.threads | quote }}
  HOST: {{ .Values.cron.env.host | quote }}
  LOG_FILE: {{ ternary .Values.cron.logFile "" (or .Values.sharedLogs.enabled (not (hasPrefix "/logs/" .Values.cron.logFile))) | quote }}
  MAX_RUNTIME_HOURS: {{ .Values.cron.env.maxRuntimeHours | quote }}
  TZ: {{ .Values.cron.env.timezone | quote }}
{{- end }}
