{{- if and .Values.cron.enabled (not .Values.cron.existingSecret) (include "duplicacy.hasCronSecretData" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "duplicacy.fullname" . }}
  labels:
    {{- include "duplicacy.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.cron.storage.endpoint1 }}
  ENDPOINT_1: {{ .Values.cron.storage.endpoint1 | quote }}
  {{- end }}
  {{- if .Values.cron.storage.endpoint2 }}
  ENDPOINT_2: {{ .Values.cron.storage.endpoint2 | quote }}
  {{- end }}
  {{- if .Values.cron.storage.bucket }}
  BUCKET: {{ .Values.cron.storage.bucket | quote }}
  {{- end }}
  {{- if .Values.cron.storage.region }}
  REGION: {{ .Values.cron.storage.region | quote }}
  {{- end }}
  {{- range $name, $creds := .Values.cron.credentials }}
  {{- $envName := regexReplaceAll "[^A-Z0-9_]" (upper $name) "_" }}
  {{- if $creds.s3Id }}
  DUPLICACY_{{ $envName }}_S3_ID: {{ $creds.s3Id | quote }}
  {{- end }}
  {{- if $creds.s3Secret }}
  DUPLICACY_{{ $envName }}_S3_SECRET: {{ $creds.s3Secret | quote }}
  {{- end }}
  {{- if $creds.password }}
  DUPLICACY_{{ $envName }}_PASSWORD: {{ $creds.password | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.cron.notification.shoutrrrUrl }}
  SHOUTRRR_URL: {{ .Values.cron.notification.shoutrrrUrl | quote }}
  {{- end }}
{{- end }}
