{{- if and .Values.web.enabled .Values.web.persistence.config.enabled (not .Values.web.persistence.config.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "duplicacy.fullname" . }}-web-config
  labels:
    {{- include "duplicacy.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  accessModes:
    {{- toYaml .Values.web.persistence.config.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.web.persistence.config.size }}
  {{- with .Values.web.persistence.config.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
